### ISSUE TITLE
`const` misused as `static`

### ISSUE THREAD

**Issue by cbeuw** [sarah-ek/gemm#7]
These global flags need to be `static`, not `const`. `const` is effectively copy+paste of the RHS, so you can't store anything at runtime.

https://github.com/sarah-ek/gemm/blob/2283886ff43f9ad2e856e595249ff90ad4912582/gemm-common/src/gemm.rs#L105-L110

**Comment by sarah-ek** [comment]
oh, thanks for noticing that. i'll fix it asap

**Comment by sarah-ek** [comment]
fixed by commit #977bbc5
